Initial
codex-team/icon-pack pull request #1
Opened 2022-06-10 12:08 UTC by talyguryn

2022-06-24 19:18 UTC, neSpecc requested changes

2022-06-24 19:18 UTC, neSpecc commented on bin/generate.js
> +for (let filename of files) {
move the processing of the single file to a separate method.

2022-06-24 19:18 UTC, neSpecc commented on bin/generate.js
> +            }
also, we need to pass `prefer viewBox` (can't remember the exact name of the option)

2022-06-24 19:18 UTC, neSpecc commented on bin/generate.js
> +    fs.writeFileSync(`./dist/icons/${exportName}.svg`, optimizedSvgString);
you're repeating the dist path several times. Lets move it to the variable

2022-06-24 19:18 UTC, neSpecc commented on bin/generate.js
> +    let iconCode = fs.readFileSync(`./src/icons/${filename}`, 'utf8');
I think we need to use the `path` package for the all path strings to make sure that it will work correctly on every OS

2022-06-24 19:29 UTC, ilyamore88 commented on .github/workflows/build-icons.yml
> +          node-version: 15
Why not LTS (16) or latest (18)?

2022-07-20 16:48 UTC, talyguryn commented
![image](https://user-images.githubusercontent.com/15259299/180037993-0a601a3b-0017-406e-b9f3-e2eaf8d1ce7f.png)

2022-07-20 20:31 UTC, ilyamore88 approved these changes

2022-07-20 21:43 UTC, neSpecc approved these changes

2022-07-21 14:51 UTC, merged